services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  authmicroservice:
    image: authmicroservice
    build:
      context: ./AuthMicroservice
    depends_on:
      - rabbitmq

  userinteractionmicroservice:
    image: userinteractionmicroservice
    build:
      context: ./UserInteractionMicroservice
    depends_on:
      - rabbitmq

  feedhandlingmicroservice:
    image: feedhandlingmicroservice
    build:
      context: ./FeedHandlingMicroservice
    depends_on:
      - rabbitmq

networks:
  default:
    external:
      name: microservices
