version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  authmicroservice:
    image: authmicroservice
    build:
      context: .
      dockerfile: AuthMicroservice/Dockerfile
    ports:
      - "8070:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started

  userinteractionmicroservice:
    image: userinteractionmicroservice
    build:
      context: .
      dockerfile: UserInteractionMicroservice/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started

  feedhandlingmicroservice:
    image: feedhandlingmicroservice
    build: 
      context: .
      dockerfile: FeedHandlingMicroservice/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started
