version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  authmicroservice:
    image: authmicroservice
    build:
      context: .
      dockerfile: AuthMicroservice/Dockerfile
    ports:
      - "8070:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started

  userinteractionmicroservice:
    image: userinteractionmicroservice
    build:
      context: .
      dockerfile: UserInteractionMicroservice/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - /UserInteractionMicroservice/Migrations:/migrations
    command: ["/bin/bash", "-c", "/opt/mssql-tools/bin/sqlcmd -U sa -P YourStrong!Passw0rd -i /migrations/create-database.sql"]

  feedhandlingmicroservice:
    image: feedhandlingmicroservice
    build: 
      context: .
      dockerfile: FeedHandlingMicroservice/Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
      apigateway:
        condition: service_started
        
  sqlserver1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver1
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_DATABASE: "AuthDb"

  sqlserver2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver2
    ports:
      - "1434:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_DATABASE: "FeedDb"

  sqlserver3:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver3
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_DATABASE: "UserIntDb"
