services:
  seq:
    image: datalust/seq
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5341/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3



  mysql_db1:
      image: mysql:latest
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: password_db1
        MYSQL_DATABASE: db1
      ports:
        - "1433:1433"
      volumes:
        - mysql_data_db1:/var/lib/mysql


volumes:
  mysql_data_db1:
  rps_seq_data1:


