services:
  seq:
    image: datalust/seq
    ports:
      - "5342:80"
      - "5341:5341"
    volumes:
      - rps_seq_data1:/data
    environment:
      - ACCEPT_EULA=Y
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5341/healthz"]
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  authmicroservice:
    image: authmicroservice
    build:
      context: ./AuthMicroservice
    depends_on:
      - rabbitmq

  userinteractionmicroservice:
    image: userinteractionmicroservice
    build:
      context: ./UserInteractionMicroservice
    depends_on:
      - rabbitmq

  feedhandlingmicroservice:
    image: feedhandlingmicroservice
    build:
      context: ./FeedHandlingMicroservice
    depends_on:
      - rabbitmq

networks:
  default:
    external:
      name: microservices


volumes:
  rps_seq_data1:

