services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile

  authmicroservice:
    image: authmicroservice
    build:
      context: .
      dockerfile: AuthMicroservice/Dockerfile
    depends_on:
      - rabbitmq
      - apigateway

  userinteractionmicroservice:
    image: userinteractionmicroservice
    build:
      context: .
      dockerfile: UserInteractionMicroservice/Dockerfile
    depends_on:
      - rabbitmq
      - apigateway

  feedhandlingmicroservice:
    image: feedhandlingmicroservice
    build: 
      context: .
      dockerfile: FeedHandlingMicroservice/Dockerfile
    depends_on:
      - rabbitmq
      - apigateway

networks:
  default:
    external:
      name: microservices
